apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | quote }}
  {{- if .Values.secretEnv.SESSION_KEY }}
  SESSION_KEY: {{ .Values.secretEnv.SESSION_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.NEO4J_PASSWORD }}
  NEO4J_PASSWORD: {{ .Values.secretEnv.NEO4J_PASSWORD | quote }}
  {{- end }}
